### ISSUE TITLE
Errors when running test

### ISSUE THREAD

**Issue by willvlad** [liquity/dev#765]
Easy to repro:

```
yarn test
```
after starting a local hardhat node

Fails on getting to test:dev-frontend with the following error:

```ProviderError: Nonce too high. Expected nonce to be 18 but got 19. Note that transactions can't be queued when automining.```

**Comment by willvlad** [comment]
When running test on contracts, it shows a ton of errors to do with gasPrice:

```
  66) Contract: TroveManager
       redeemCollateral(): a redemption made at zero base increases the ETH-fees-per-LQTY-staked in LQTY Staking contract:
     Error: Returned error: Transaction gasPrice (0) is too low for the next block, which has a baseFeePerGas of 7
      at Function.performRedemptionTx (utils/testHelpers.js:1257:45)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at Function.redeemCollateral (utils/testHelpers.js:1205:16)
      at Context.<anonymous> (test/TroveManagerTest.js:3882:5)

  67) Contract: TroveManager
       redeemCollateral(): a redemption made at a non-zero base rate send a non-zero ETHFee to LQTY staking contract:
     Error: Returned error: Transaction gasPrice (0) is too low for the next block, which has a baseFeePerGas of 7
      at Function.performRedemptionTx (utils/testHelpers.js:1257:45)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at Function.redeemCollateral (utils/testHelpers.js:1205:16)
      at Context.<anonymous> (test/TroveManagerTest.js:3915:5)

  68) Contract: TroveManager
       redeemCollateral(): a redemption made at a non-zero base rate increases ETH-per-LQTY-staked in the staking contract:
     Error: Returned error: Transaction gasPrice (0) is too low for the next block, which has a baseFeePerGas of 7
      at Function.performRedemptionTx (utils/testHelpers.js:1257:45)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at Function.redeemCollateral (utils/testHelpers.js:1205:16)
      at Context.<anonymous> (test/TroveManagerTest.js:3957:5)

  69) Contract: TroveManager
       redeemCollateral(): a redemption sends the ETH remainder (ETHDrawn - ETHFee) to the redeemer:
     Error: Returned error: Transaction gasPrice (0) is too low for the next block, which has a baseFeePerGas of 7
      at Function.performRedemptionTx (utils/testHelpers.js:1257:45)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at Function.redeemCollateral (utils/testHelpers.js:1205:16)
      at Context.<anonymous> (test/TroveManagerTest.js:4009:5)

  70) Contract: TroveManager
       redeemCollateral(): a full redemption (leaving trove with 0 debt), closes the trove:
     Error: Returned error: Transaction gasPrice (0) is too low for the next block, which has a baseFeePerGas of 7
      at Function.performRedemptionTx (utils/testHelpers.js:1257:45)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at Function.redeemCollateral (utils/testHelpers.js:1205:16)
      at Context.<anonymous> (test/TroveManagerTest.js:4052:5)

  71) Contract: TroveManager
       redeemCollateral(): emits correct debt and coll values in each redeemed trove's TroveUpdated event:
     Error: Returned error: Transaction gasPrice (0) is too low for the next block, which has a baseFeePerGas of 7
      at Function.performRedemptionTx (utils/testHelpers.js:1257:45)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at Function.redeemCollateralAndGetTxObject (utils/testHelpers.js:1217:16)
      at Context.<anonymous> (test/TroveManagerTest.js:4157:26)

  72) Contract: TroveManager
       redeemCollateral(): a redemption that closes a trove leaves the trove's ETH surplus (collateral - ETH drawn) available for the trove owner to claim:
     Error: Returned error: Transaction gasPrice (0) is too low for the next block, which has a baseFeePerGas of 7
      at Function.performRedemptionTx (utils/testHelpers.js:1257:45)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at Function.redeemCollateral (utils/testHelpers.js:1205:16)
      at redeemCollateral3Full1Partial (test/TroveManagerTest.js:4092:5)
      at Context.<anonymous> (test/TroveManagerTest.js:4195:9)

  73) Contract: TroveManager
       redeemCollateral(): a redemption that closes a trove leaves the trove's ETH surplus (collateral - ETH drawn) available for the trove owner after re-opening trove:
     Error: Returned error: Transaction gasPrice (0) is too low for the next block, which has a baseFeePerGas of 7
      at Function.performRedemptionTx (utils/testHelpers.js:1257:45)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at Function.redeemCollateral (utils/testHelpers.js:1205:16)
      at redeemCollateral3Full1Partial (test/TroveManagerTest.js:4092:5)
      at Context.<anonymous> (test/TroveManagerTest.js:4224:9)

  74) Contract: TroveManager
       redeemCollateral(): reverts if fee eats up all returned collateral:
     Error: Returned error: Transaction gasPrice (0) is too low for the next block, which has a baseFeePerGas of 7
      at Context.<anonymous> (test/TroveManagerTest.js:4282:47)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Is there a setting to be changed or a different package / node version to be used for testing?

**Comment by willvlad** [comment]
@danielattilasimon - do you know what might be going wrong?

**Comment by bingen** [comment]
If I recall correctly, this is because contracts package is missing update for EIP-1559. See: https://github.com/liquity/dev/commit/777ec9081c13073797bfb510e73f81d1c2bd4c9f

**Comment by willvlad** [comment]
@bingen thanks, but if it's been merged by that commit, shouldn't it be there in the current version? 

Can you confirm what needs to be done to update it?

**Comment by bingen** [comment]
That’s just an example of the issue, but in another package. `contracts` package tests should be fixed so they don’t send zero gas price.

**Comment by willvlad** [comment]
Ok, replaced gasPrice: 0 everywhere in the tests folder. Now getting other errors like these:

```
 1) Contract: BorrowerOperations
       Without proxy
         closeTrove(): sends the correct amount of ETH to the user:

      AssertionError: expected false to be true
      + expected - actual

      -false
      +true
      
      at Context.<anonymous> (test/BorrowerOperationsTest.js:4311:16)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

  2) Contract: Gas compensation tests
       Gas compensation from pool-offset liquidations. All collateral paid as compensation:
     AssertionError: expected '105024999996650128' to equal <BN: 1751fae59891000>
      at Context.<anonymous> (test/GasCompensationTest.js:451:12)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

  3) Contract: Gas compensation tests
       gas compensation from pool-offset liquidations: 0.5% collateral < $10 in value. Compensates $10 worth of collateral, liquidates the remainder:
     AssertionError: expected '55024999996790024' to equal <BN: c37cf22ac41000>
      at Context.<anonymous> (test/GasCompensationTest.js:606:12)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

  4) Contract: Gas compensation tests
       gas compensation from pool-offset liquidations: 0.5% collateral > $10 in value. Compensates 0.5% of  collateral, liquidates the remainder:
     AssertionError: expected '100249999996790024' to equal <BN: 16428d806bba000>
      at Context.<anonymous> (test/GasCompensationTest.js:733:12)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

  5) Contract: Gas compensation tests
       liquidateTroves(): full offset.  Compensates the correct amount, and liquidates the remainder:
     AssertionError: expected <BN: 2ba2f8f01bc8a000> to equal '3144349199995694000'
      at Context.<anonymous> (test/GasCompensationTest.js:1209:12)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

  6) Contract: Gas compensation tests
       liquidateTroves(): full redistribution. Compensates the correct amount, and liquidates the remainder:

      AssertionError: expected 3904152 to be at most 1000
      + expected - actual

      -3904152
      +1000
      
      at Context.<anonymous> (test/GasCompensationTest.js:1303:12)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

  7) Contract: LQTYStaking revenue share tests
       LQTY Staking: A single staker earns all ETH and LQTY fees that occur:

      AssertionError: expected 1089830 to be at most 1000
      + expected - actual

      -1089830
      +1000
      
      at Context.<anonymous> (test/LQTYStakingFeeRewardsTest.js:421:12)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

  8) Contract: LQTYStaking revenue share tests
       stake(): Top-up sends out all accumulated ETH and LUSD gains to the staker:

      AssertionError: expected 1026810 to be at most 1000
      + expected - actual

      -1026810
      +1000
      
      at Context.<anonymous> (test/LQTYStakingFeeRewardsTest.js:517:12)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

  9) Contract: LQTYStaking revenue share tests
       LQTY Staking: Multiple stakers earn the correct share of all ETH and LQTY fees, based on their stake size:

      AssertionError: expected 1166683 to be at most 1000
      + expected - actual

      -1166683
      +1000
      
      at Context.<anonymous> (test/LQTYStakingFeeRewardsTest.js:877:12)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

  10) Contract: BorrowerWrappers
       proxy owner can recover ETH:
     AssertionError: expected <BN: de0b6b3a75f1b08> to equal '1000000000000000000'
      at Context.<anonymous> (test/ProxyBorrowerWrappersScript.js:124:12)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

  11) Contract: StabilityPool
       Stability Pool Mechanisms
         provideToSP(), new deposit: depositor does not receive ETH gains:

      AssertionError: expected '999999999998870299515840791560205994' to equal '999999999998870299515840791562287098'
      + expected - actual

      -999999999998870299515840791560205994
      +999999999998870299515840791562287098
      
      at Context.<anonymous> (test/StabilityPoolTest.js:1411:14)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

  12) Contract: StabilityPool
       Stability Pool Mechanisms
         provideToSP(), new deposit after past full withdrawal: depositor does not receive ETH gains:

      AssertionError: expected '999999999998870300464855591557716826' to equal '999999999998870300464855591560205994'
      + expected - actual

      -999999999998870300464855591557716826
      +999999999998870300464855591560205994
      
      at Context.<anonymous> (test/StabilityPoolTest.js:1491:14)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

  13) Contract: StabilityPool
       Stability Pool Mechanisms
         withdrawFromSP(): succeeds when amount is 0 and system has an undercollateralized trove:

      AssertionError: expected false to be true
      + expected - actual

      -false
      +true
      
      at Context.<anonymous> (test/StabilityPoolTest.js:2796:14)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

  14) Contract: StabilityPool
       Stability Pool Mechanisms
         withdrawFromSP(): caller can withdraw full deposit and ETH gain during Recovery Mode:

      AssertionError: expected '999999999999858510878274304359916148' to equal '999999999999858510878274304358351228'
      + expected - actual

      -999999999999858510878274304359916148
      +999999999999858510878274304358351228
      
      at Context.<anonymous> (test/StabilityPoolTest.js:3176:14)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

  15) Contract: TroveManager - in Recovery Mode
       liquidate(), with 110% < ICR < TCR, and StabilityPool LUSD > debt to liquidate: offsets the trove entirely with the pool:

      AssertionError: expected 314520 to be at most 1000
      + expected - actual

      -314520
      +1000
      
      at Function.assertIsApproximatelyEqual (utils/testHelpers.js:73:12)
      at Context.<anonymous> (test/TroveManager_RecoveryModeTest.js:784:8)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

  16) Contract: TroveManager - in Recovery Mode
       liquidate(), with  110% < ICR < TCR, and StabilityPool LUSD > debt to liquidate: removes stake and updates totalStakes:

      AssertionError: expected 314520 to be at most 1000
      + expected - actual

      -314520
      +1000
      
      at Function.assertIsApproximatelyEqual (utils/testHelpers.js:73:12)
      at Context.<anonymous> (test/TroveManager_RecoveryModeTest.js:915:8)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

  17) Contract: TroveManager - in Recovery Mode
       liquidate(), with 110% < ICR < TCR, and StabilityPool LUSD > debt to liquidate: closes the Trove:

      AssertionError: expected 314520 to be at most 1000
      + expected - actual

      -314520
      +1000
      
      at Function.assertIsApproximatelyEqual (utils/testHelpers.js:73:12)
      at Context.<anonymous> (test/TroveManager_RecoveryModeTest.js:1034:8)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

  18) Contract: TroveManager - in Recovery Mode
       liquidate(), with 110% < ICR < TCR, and StabilityPool LUSD > debt to liquidate: can liquidate troves out of order:

      AssertionError: expected false to be true
      + expected - actual

      -false
      +true
      
      at Context.<anonymous> (test/TroveManager_RecoveryModeTest.js:1139:12)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

  19) Contract: TroveManager - in Recovery Mode
       liquidate(), with 110% < ICR < TCR, can claim collateral, re-open, be reedemed and claim again:

      AssertionError: expected 314520 to be at most 1000
      + expected - actual

      -314520
      +1000
      
      at Function.assertIsApproximatelyEqual (utils/testHelpers.js:73:12)
      at Context.<anonymous> (test/TroveManager_RecoveryModeTest.js:2033:8)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

  20) Contract: TroveManager - in Recovery Mode
       liquidate(), with 110% < ICR < TCR, can claim collateral, after another claim from a redemption:

      AssertionError: expected 314520 to be at most 1000
      + expected - actual

      -314520
      +1000
      
      at Function.assertIsApproximatelyEqual (utils/testHelpers.js:73:12)
      at Context.<anonymous> (test/TroveManager_RecoveryModeTest.js:2094:8)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

  21) Contract: TroveManager - in Recovery Mode
       liquidateTroves(): emits liquidation event with correct values when all troves have ICR > 110% and Stability Pool covers a subset of troves:

      AssertionError: expected 352920 to be at most 1000
      + expected - actual

      -352920
      +1000
      
      at Function.assertIsApproximatelyEqual (utils/testHelpers.js:73:12)
      at Context.<anonymous> (test/TroveManager_RecoveryModeTest.js:2961:8)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

  22) Contract: TroveManager - in Recovery Mode
       liquidateTroves():  emits liquidation event with correct values when all troves have ICR > 110% and Stability Pool covers a subset of troves, including a partial:

      AssertionError: expected 352920 to be at most 1000
      + expected - actual

      -352920
      +1000
      
      at Function.assertIsApproximatelyEqual (utils/testHelpers.js:73:12)
      at Context.<anonymous> (test/TroveManager_RecoveryModeTest.js:3085:8)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

  23) Contract: TroveManager - in Recovery Mode
       liquidateTroves() with a non fullfilled liquidation: emits correct liquidation event values:

      AssertionError: expected 352920 to be at most 1000
      + expected - actual

      -352920
      +1000
      
      at Function.assertIsApproximatelyEqual (utils/testHelpers.js:73:12)
      at Context.<anonymous> (test/TroveManager_RecoveryModeTest.js:3794:8)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

  24) Contract: TroveManager - in Recovery Mode
       batchLiquidateTroves() with a non fullfilled liquidation: emits correct liquidation event values:

      AssertionError: expected 352920 to be at most 1000
      + expected - actual

      -352920
      +1000
      
      at Function.assertIsApproximatelyEqual (utils/testHelpers.js:73:12)
      at Context.<anonymous> (test/TroveManager_RecoveryModeTest.js:4642:8)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

  25) Contract: TroveManager - in Recovery Mode
       batchLiquidateTroves(): emits liquidation event with correct values when all troves have ICR > 110% and Stability Pool covers a subset of troves:

      AssertionError: expected 352920 to be at most 1000
      + expected - actual

      -352920
      +1000
      
      at Function.assertIsApproximatelyEqual (utils/testHelpers.js:73:12)
      at Context.<anonymous> (test/TroveManager_RecoveryModeTest.js:5142:8)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

  26) Contract: TroveManager - in Recovery Mode
       batchLiquidateTroves(): emits liquidation event with correct values when all troves have ICR > 110% and Stability Pool covers a subset of troves, including a partial:

      AssertionError: expected 352920 to be at most 1000
      + expected - actual

      -352920
      +1000
      
      at Function.assertIsApproximatelyEqual (utils/testHelpers.js:73:12)
      at Context.<anonymous> (test/TroveManager_RecoveryModeTest.js:5259:8)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

  27) Contract: TroveManager
       redeemCollateral(): cancels the provided LUSD with debt from Troves with the lowest ICRs and sends an equivalent amount of Ether:

      AssertionError: expected 3732432 to be at most 1000
      + expected - actual

      -3732432
      +1000
      
      at Function.assertIsApproximatelyEqual (utils/testHelpers.js:73:12)
      at Context.<anonymous> (test/TroveManagerTest.js:2747:8)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

  28) Contract: TroveManager
       redeemCollateral(): with invalid first hint, zero address:

      AssertionError: expected 3721168 to be at most 1000
      + expected - actual

      -3721168
      +1000
      
      at Function.assertIsApproximatelyEqual (utils/testHelpers.js:73:12)
      at Context.<anonymous> (test/TroveManagerTest.js:2844:8)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

  29) Contract: TroveManager
       redeemCollateral(): with invalid first hint, non-existent trove:

      AssertionError: expected 3747032 to be at most 1000
      + expected - actual

      -3747032
      +1000
      
      at Function.assertIsApproximatelyEqual (utils/testHelpers.js:73:12)
      at Context.<anonymous> (test/TroveManagerTest.js:2941:8)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

  30) Contract: TroveManager
       redeemCollateral(): with invalid first hint, trove below MCR:

      AssertionError: expected 3986136 to be at most 1000
      + expected - actual

      -3986136
      +1000
      
      at Function.assertIsApproximatelyEqual (utils/testHelpers.js:73:12)
      at Context.<anonymous> (test/TroveManagerTest.js:3043:8)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

  31) Contract: TroveManager
       redeemCollateral(): doesnt perform the final partial redemption in the sequence if the hint is out-of-date:

      AssertionError: expected 3074208 to be at most 1000
      + expected - actual

      -3074208
      +1000
      
      at Function.assertIsApproximatelyEqual (utils/testHelpers.js:73:12)
      at Context.<anonymous> (test/TroveManagerTest.js:3405:8)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

  32) Contract: TroveManager
       redeemCollateral(): a redemption sends the ETH remainder (ETHDrawn - ETHFee) to the redeemer:

      AssertionError: expected 2231456 to be at most 100000
      + expected - actual

      -2231456
      +100000
      
      at Function.assertIsApproximatelyEqual (utils/testHelpers.js:73:12)
      at Context.<anonymous> (test/TroveManagerTest.js:4920:8)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

  33) Contract: TroveManager
       redeemCollateral(): a redemption that closes a trove leaves the trove's ETH surplus (collateral - ETH drawn) available for the trove owner to claim:

      AssertionError: expected 352920 to be at most 1000
      + expected - actual

      -352920
      +1000
      
      at Function.assertIsApproximatelyEqual (utils/testHelpers.js:73:12)
      at Context.<anonymous> (test/TroveManagerTest.js:5213:8)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

  34) Contract: TroveManager
       redeemCollateral(): a redemption that closes a trove leaves the trove's ETH surplus (collateral - ETH drawn) available for the trove owner after re-opening trove:

      AssertionError: expected 352920 to be at most 1000
      + expected - actual

      -352920
      +1000
      
      at Function.assertIsApproximatelyEqual (utils/testHelpers.js:73:12)
      at Context.<anonymous> (test/TroveManagerTest.js:5278:8)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

```

Any thoughts why the gasPrice change would cause these?

**Comment by willvlad** [comment]
Do you guys have an earlier commit with tests completing without errors?

**Comment by bingen** [comment]
> Any thoughts why the gasPrice change would cause these?

Yes, gas price was set to zero because it makes way easier to check movements of ETH. Otherwise you have to do the math and account for the ETH spent in the transaction.

**Comment by bingen** [comment]
> Do you guys have an earlier commit with tests completing without errors?

Yes, for instance:

https://github.com/liquity/dev/releases/tag/mainnet_coverage
https://github.com/liquity/dev/pull/514

**Comment by wollooo** [comment]
@willvlad all test fixed.
Please take a lot [here](https://github.com/kumodao/borrowprot/issues/12)

**Comment by bingen** [comment]
Oh, nice, feel free to open a PR to our repo with the fixes too. Thanks!

**Comment by hcheng826** [comment]
hmmm i have the same error message when I run `yarn start-dev-chain`. Any ideas?
